### ISSUE TITLE
Realtime download progress

### ISSUE THREAD

**Issue by nana-desu** [ssseasonnn/RxDownload#305]
I successfully retrieving download data with TaskRecord, but need to get realtime update listener from other activities. Download starts from "BrowserActivity.kt" and "DownloadsActivity.kt" act as a list of downloaded progress. Any listener to handle that? Thank you 

![ezgif-3-755b14e359eb](https://user-images.githubusercontent.com/59090734/76276123-9bc2e600-62b7-11ea-8813-3cfdc6d4c7eb.gif)

**Comment by ssseasonnn** [comment]
Use the same task to re-subscribe in different activities.

**Comment by nana-desu** [comment]
Ok I found you've implemented on demo

**Comment by nana-desu** [comment]
Sorry, I reopen this case. 
How to retry after download failed in specific times?
Also, I need to catch when failed download returns "Chunked can not get totalSize!", this happened on certain websites

**Comment by ssseasonnn** [comment]
This means that your url does not support breakpoint download, and its transmission method is Chunked. In this case, we cannot get the totalSize

**Comment by ssseasonnn** [comment]
When the download fails, restart it.

**Comment by nana-desu** [comment]
ok.. last one
it's possible to make an action with data source items from renderStatus? 
I use BottomSheetDialog and need to remove the item from recycler

**Comment by ssseasonnn** [comment]
you can render a empty status item, or setState = null

**Comment by nana-desu** [comment]
Can you provide an example?
I'm stuck with this
```kotlin
private fun renderStatus(scope: YashaScope<DownloadAdapterItem>, it: Status, context: Context) {
  scope.apply {
    when(it) {
      is Completed -> {
         bottomSheetDialog.apply {
            show()
            tv_delete.apply {
                delete()
                -- remove the item from recycler like datasource.removeItem() does --
                dismiss()
            }
         }
      }
    }
  }
}
```

Thank you

**Comment by ssseasonnn** [comment]
I understand, you can only use dataSource to remove items, no direct action

**Comment by ssseasonnn** [comment]
Maybe you can use livedata to send an event and then listen in the activity to delete this item

**Comment by nana-desu** [comment]
> This means that your url does not support breakpoint download, and its transmission method is Chunked. In this case, we cannot get the totalSize

I know, but how to achieve with try catch or disabling breakpoint?

**Comment by nana-desu** [comment]
Try to catch with no luck
``` kotlin
    when (it) {
      is Normal -> try {
       
      } catch (e: Throwable) {
      }
      is Failed -> try {
        Handler().postDelayed({ task.start() },2000) 
      } catch (e: Throwable) {
      }
      is Started -> try {
      } catch (e: Throwable) {
      }
      is Downloading -> try {
      } catch (e: Throwable) {
      }
    }
```

**Comment by nana-desu** [comment]
> This means that your url does not support breakpoint download, and its transmission method is Chunked. In this case, we cannot get the totalSize

I use isChunked from status to catch those errors. but sometimes crashes on certain devices

``` kotlin
 is Normal, is Started, is Failed, is Downloading -> {
        if (it.progress.isChunked) {
            taskManager.stop()
            Handler().postDelayed({
              taskManager.start()
            }, 3000)
        }
}
```



![image](https://user-images.githubusercontent.com/59090734/76521223-f5353b80-6496-11ea-9e14-2daf7e33e08c.png)

**Comment by nana-desu** [comment]
> This means that your url does not support breakpoint download, and its transmission method is Chunked. In this case, we cannot get the totalSize

I use isChunked from status to catch those errors. but sometimes crashes on certain devices

``` kotlin
 is Normal, is Started, is Failed, is Downloading -> {
        if (it.progress.isChunked) {
            taskManager.stop()
            Handler().postDelayed({
              taskManager.start()
            }, 3000)
        }
}
```



![image](https://user-images.githubusercontent.com/59090734/76521223-f5353b80-6496-11ea-9e14-2daf7e33e08c.png)

**Comment by ssseasonnn** [comment]
Got it, fix it later

**Comment by nana-desu** [comment]
![image](https://user-images.githubusercontent.com/59090734/76582295-6a8d2480-6508-11ea-958d-14b7885c3231.png)
![image](https://user-images.githubusercontent.com/59090734/76582310-7973d700-6508-11ea-8bc6-da7d382d8bdf.png)

**Comment by nana-desu** [comment]
Please add setOngoing to prevent notification swipe while the download is running on NotificationCompat. 
Maybe you need to define Quadruple to set "setOngoing" value inside SimpleNotificationCreator

**Comment by nana-desu** [comment]
this crash happened when downloading from zippyshare

**Comment by nana-desu** [comment]
I also getting error when trying to stop or pause
```
java.net.SocketException: Socket closed
        at com.android.org.conscrypt.NativeCrypto.SSL_read(NativeCrypto.java:-2)
        at com.android.org.conscrypt.NativeSsl.read(NativeSsl.java:399)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:546)
        at okio.InputStreamSource.read(Okio.kt:93)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
        at okio.RealBufferedSource.read(RealBufferedSource.kt:188)
        at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.kt:349)
        at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.kt:386)
        at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276)
        at okio.RealBufferedSource.read(RealBufferedSource.kt:188)
        at okio.ForwardingSource.read(ForwardingSource.kt:29)
        at retrofit2.OkHttpCall$ExceptionCatchingResponseBody$1.read(OkHttpCall.java:288)
        at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158)
        at java.io.InputStream.read(InputStream.java:101)
        at zlc.season.rxdownload4.downloader.RangeDownloader$InnerDownloader$rangeSave$2.accept(RangeDownloader.kt:152)
        at zlc.season.rxdownload4.downloader.RangeDownloader$InnerDownloader$rangeSave$2.accept(RangeDownloader.kt:123)
        at io.reactivex.internal.operators.flowable.FlowableInternalHelper$SimpleBiGenerator.apply(FlowableInternalHelper.java:62)
        at io.reactivex.internal.operators.flowable.FlowableInternalHelper$SimpleBiGenerator.apply(FlowableInternalHelper.java:53)
        at io.reactivex.internal.operators.flowable.FlowableGenerate$GeneratorSubscription.request(FlowableGenerate.java:109)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onSubscribe(FlowableFlatMap.java:661)
        at io.reactivex.internal.operators.flowable.FlowableGenerate.subscribeActual(FlowableGenerate.java:52)
        at io.reactivex.Flowable.subscribe(Flowable.java:14935)
        at io.reactivex.Flowable.subscribe(Flowable.java:14882)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.tryEmit(FlowableFlatMap:282)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onNext(FlowableFlatMap.java:668)
        at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.drain(FlowableOnBackpressureLatest.java:129)
        at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.onNext(FlowableOnBackpressureLatest.java:68)
        at io.reactivex.internal.operators.flowable.FlowableFromObservable$SubscriberObserver.onNext(FlowableFromObservable.java:54)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:47)
```

Added RxJavaPlugins.setErrorHandler on Application but still not helping
```
 RxJavaPlugins.setErrorHandler { throwable ->
      if (throwable is UndeliverableException) {
        throwable.cause?.let {
          Thread.currentThread().uncaughtExceptionHandler?.uncaughtException(
            Thread.currentThread(),
            it
          )
          return@setErrorHandler
        }
      }
      if (throwable is IOException || throwable is SocketException) {
        // fine, irrelevant network problem or API that throws on cancellation
        return@setErrorHandler
      }
      if (throwable is InterruptedException) {
        // fine, some blocking code was interrupted by a dispose call
        return@setErrorHandler
      }
      if (throwable is NullPointerException || throwable is IllegalArgumentException) {
        // that's likely a bug in the application
        Thread.currentThread().uncaughtExceptionHandler?.uncaughtException(
          Thread.currentThread(),
          throwable
        )
        return@setErrorHandler
      }
      if (throwable is IllegalStateException) {
        // that's a bug in RxJava or in a custom operator
        Thread.currentThread().uncaughtExceptionHandler?.uncaughtException(
          Thread.currentThread(),
          throwable
        )
        return@setErrorHandler
      }
    }
```

**Comment by nana-desu** [comment]
any progress? hope I can disable breakpoint like other download manager libraries in github does. or at least throwing those errors

**Comment by ssseasonnn** [comment]
fixed, 1.1.2

**Comment by nana-desu** [comment]
I have added this to catch RxJava global errors in Application
```
RxJavaPlugins.setErrorHandler {
      if (it is UndeliverableException) {
        //do nothing
      } else {
        it.log()
      }
    }
```
But when i pause/stop the download, sometimes i got error "Socket Closed"
Any solution?

**Comment by nana-desu** [comment]
I still getting an error

```
java.lang.IllegalStateException: Chunked can not get percent!
        at zlc.season.rxdownload4.Progress.percent(Progress.kt:33)
        at com.usamin.app.adapter.DownloadAdapterItem.renderStatus(DownloadsAdapterSource.kt:92)
        at com.usamin.app.adapter.DownloadAdapterItem.access$renderStatus(DownloadAdapterItem:70)
```

``` tv_percent.text = it.progress.percentStr() ```

https://github.com/ssseasonnn/RxDownload/blob/21e4e66602f150bd38c7464fe2e96cdbd4c79080/rxdownload4/src/main/java/zlc/season/rxdownload4/Progress.kt#L33

**Comment by ssseasonnn** [comment]
When you display progress on the UI, first determine isChunked. If it is true, set the indeterminate property of the progressbar to true

**Comment by ssseasonnn** [comment]
Because chunked download can not get totalSize, so you can not show real progress

**Comment by nana-desu** [comment]
ok, i fix by added
```
if(!it.progress.isChunked) {
          tv_percent.text = it.progress.percentStr()
        }
```

now the main problem with RxJava error.  Sometimes got socket closed, response is null, etc
I have added this but still not working
![image](https://user-images.githubusercontent.com/59090734/77136599-ebff2c80-6a9d-11ea-88dc-b602c780b713.png)

**Comment by nana-desu** [comment]
```
 if (!it.progress.isChunked) {
          tv_size.text = it.progress.totalSizeStr()
          tv_percent.text = it.progress.percentStr()
        }
```

but still getting 
java.lang.IllegalArgumentException: Size must larger than 0.

**Comment by nana-desu** [comment]
I ended by adding try catch for every progress, using isChunked still doesn't work,
Better to set it to 0 first, rather than throwing an Exception

**Comment by nana-desu** [comment]
Even try catch inside status listener to handle the error and adding RxJavaPlugins.setErrorHandler.
Still getting rxjava errors. I frustrated getting too much error with this library.

**Comment by nana-desu** [comment]
Even try catch inside status listener to handle the error and adding RxJavaPlugins.setErrorHandler.
Still getting rxjava errors. I frustrated getting too much error with this library.

**Comment by nana-desu** [comment]
```
java.net.SocketException: Socket closed
        at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_read(:com.google.android.gms@200616020@20.06.16 (040406-296104215):-2)
        at com.google.android.gms.org.conscrypt.NativeSsl.read(:com.google.android.gms@200616020@20.06.16 (040406-296104215):3)
        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(:com.google.android.gms@200616020@20.06.16 (040406-296104215):7)
        at okio.InputStreamSource.read(Okio.kt:93)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
        at okio.RealBufferedSource.read(RealBufferedSource.kt:188)
        at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.kt:349)
        at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.kt:386)
        at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276)
        at okio.RealBufferedSource.read(RealBufferedSource.kt:188)
        at okio.ForwardingSource.read(ForwardingSource.kt:29)
        at retrofit2.OkHttpCall$ExceptionCatchingResponseBody$1.read(OkHttpCall.java:288)
        at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158)
        at java.io.InputStream.read(InputStream.java:101)
        at zlc.season.rxdownload4.downloader.RangeDownloader$InnerDownloader$rangeSave$2.accept(RangeDownloader.kt:152)
        at zlc.season.rxdownload4.downloader.RangeDownloader$InnerDownloader$rangeSave$2.accept(RangeDownloader.kt:123)
        at io.reactivex.internal.operators.flowable.FlowableInternalHelper$SimpleBiGenerator.apply(FlowableInternalHelper.java:62)
        at io.reactivex.internal.operators.flowable.FlowableInternalHelper$SimpleBiGenerator.apply(FlowableInternalHelper.java:53)
        at io.reactivex.internal.operators.flowable.FlowableGenerate$GeneratorSubscription.request(FlowableGenerate.java:109)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onSubscribe(FlowableFlatMap.java:661)
        at io.reactivex.internal.operators.flowable.FlowableGenerate.subscribeActual(FlowableGenerate.java:52)
        at io.reactivex.Flowable.subscribe(Flowable.java:14935)
        at io.reactivex.Flowable.subscribe(Flowable.java:14882)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.tryEmit(FlowableFlatMap:282)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onNext(FlowableFlatMap.java:668)
        at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.drain(FlowableOnBackpressureLatest.java:129)
        at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.onNext(FlowableOnBackpressureLatest.java:68)
        at io.reactivex.internal.operators.flowable.FlowableFromObservable$SubscriberObserver.onNext(FlowableFromObservable.java:54)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:47)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by nana-desu** [comment]
still getting Chunked error ...
should i adding try catch for every progress?

`` 
try {
progress_bar?.let { d ->
          d.isIndeterminate = it.progress.isChunked
          d.max = 100
          d.progress = it.progress.percent().toInt()
        }
} catch(e: Throwable) {

}
```

**Comment by nana-desu** [comment]
Please change this
https://github.com/ssseasonnn/RxDownload/blob/21e4e66602f150bd38c7464fe2e96cdbd4c79080/rxdownload4/src/main/java/zlc/season/rxdownload4/Progress.kt#L33
to
```
return if(isChunked) {
          0.0
        } else {
          downloadSize ratio totalSize  
        }
```

and
https://github.com/ssseasonnn/RxDownload/blob/1250f5135dd091cc866e3bc0ce7d12e85751db93/rxdownload4/src/main/java/zlc/season/rxdownload4/utils/Util.kt#L20

to

```
return if(this >= 0) {
      when {
        tb >= 1 -> "${tb.decimal(2)} TB"
        gb >= 1 -> "${gb.decimal(2)} GB"
        mb >= 1 -> "${mb.decimal(2)} MB"
        kb >= 1 -> "${kb.decimal(2)} KB"
        else -> "${byte.decimal(2)} B"
      }
    } else {
      "0.0 B"
    }
```

Catch with throwable or using isChunked doesn't work
